// areas.dart
// Shared list of Bangalore neighborhoods, used wherever a user picks their
// home area — signup, league creation/editing, profile editing, and the
// browse-leagues area filter. Now one entry among several in `areasByCity`
// below (see cities.dart) — kept as its own top-level constant rather than
// inlined into the map so existing references to it keep working unchanged.
const List<String> bangaloreAreas = [
  'Koramangala',
  'Indiranagar',
  'HSR Layout',
  'BTM Layout',
  'Jayanagar',
  'JP Nagar',
  'Whitefield',
  'Marathahalli',
  'Electronic City',
  'Bellandur',
  'Sarjapur Road',
  'Hebbal',
  'Yelahanka',
  'Malleshwaram',
  'Rajajinagar',
  'Basavanagudi',
  'Banashankari',
  'RT Nagar',
  'Frazer Town',
  'Ulsoor',
  'MG Road',
  'Domlur',
  'CV Raman Nagar',
  'Kalyan Nagar',
  'Banaswadi',
  'Vijayanagar',
  'Rajarajeshwari Nagar',
  'Kengeri',
  'Yeshwanthpur',
  'Nagarbhavi',
  'Hennur',
  'Bannerghatta Road',
  'KR Puram',
  'Mahadevapura',
  'Uttarahalli',
  'Kanakapura Road',
  'Konanakunte',
  'Anjanapura',
  'Padmanabhanagar',
  'Girinagar',
  'Kumaraswamy Layout',
  'Vasanthapura',
  'Chikkalasandra',
  'Hulimavu',
  'Bommanahalli',
  'Begur',
  'Arekere',
  'Gottigere',
  'Silk Board',
  'Madiwala',
  'Bilekahalli',
  'Kudlu',
];

// Every other city's neighborhood list, keyed by the same strings used in
// cities.dart's `indianCities`. Area pickers should look up
// `areasByCity[selectedCity] ?? []` rather than assuming `bangaloreAreas`.
const Map<String, List<String>> areasByCity = {
  'Bangalore': bangaloreAreas,
  'Mumbai': [
    'Andheri',
    'Bandra',
    'Juhu',
    'Powai',
    'Malad',
    'Borivali',
    'Goregaon',
    'Dadar',
    'Worli',
    'Lower Parel',
    'Colaba',
    'Chembur',
    'Ghatkopar',
    'Kandivali',
    'Vile Parle',
    'Santacruz',
    'Thane',
    'Navi Mumbai',
    'Mulund',
    'Kurla',
    'Vikhroli',
    'Versova',
    'Kharghar',
    'Vashi',
  ],
  'Delhi NCR': [
    'Connaught Place',
    'Saket',
    'Vasant Kunj',
    'Dwarka',
    'Rohini',
    'Karol Bagh',
    'Lajpat Nagar',
    'Hauz Khas',
    'Greater Kailash',
    'Janakpuri',
    'Pitampura',
    'Rajouri Garden',
    'Mayur Vihar',
    'Preet Vihar',
    'Gurgaon',
    'Noida',
    'Faridabad',
    'Ghaziabad',
    'South Extension',
    'Chanakyapuri',
    'Punjabi Bagh',
    'Model Town',
    'Vasant Vihar',
  ],
  'Hyderabad': [
    'Banjara Hills',
    'Jubilee Hills',
    'Gachibowli',
    'Hitech City',
    'Madhapur',
    'Kondapur',
    'Kukatpally',
    'Secunderabad',
    'Begumpet',
    'Ameerpet',
    'Miyapur',
    'Manikonda',
    'Somajiguda',
    'Himayatnagar',
    'Uppal',
    'LB Nagar',
    'Dilsukhnagar',
    'Attapur',
    'Nizampet',
  ],
  'Chennai': [
    'T Nagar',
    'Adyar',
    'Anna Nagar',
    'Velachery',
    'Nungambakkam',
    'Mylapore',
    'Besant Nagar',
    'OMR',
    'Porur',
    'Tambaram',
    'Kilpauk',
    'Guindy',
    'Ashok Nagar',
    'Vadapalani',
    'Perambur',
    'Chromepet',
    'Sholinganallur',
    'Alwarpet',
    'Egmore',
  ],
  'Kolkata': [
    'Salt Lake',
    'Park Street',
    'Ballygunge',
    'Gariahat',
    'New Town',
    'Behala',
    'Howrah',
    'Alipore',
    'Dum Dum',
    'Jadavpur',
    'Tollygunge',
    'Rajarhat',
    'Garia',
    'Kasba',
    'Lake Town',
    'Shyambazar',
    'Beliaghata',
  ],
  'Pune': [
    'Koregaon Park',
    'Kothrud',
    'Baner',
    'Aundh',
    'Viman Nagar',
    'Hinjewadi',
    'Wakad',
    'Hadapsar',
    'Kharadi',
    'Camp',
    'Deccan Gymkhana',
    'Shivaji Nagar',
    'Magarpatta',
    'Kalyani Nagar',
    'Wagholi',
    'Pimpri-Chinchwad',
    'Warje',
    'Bavdhan',
  ],
  'Ahmedabad': [
    'Navrangpura',
    'Satellite',
    'Bodakdev',
    'Vastrapur',
    'Maninagar',
    'Paldi',
    'CG Road',
    'SG Highway',
    'Prahlad Nagar',
    'Bopal',
    'Thaltej',
    'Naranpura',
    'Vastral',
    'Chandkheda',
    'Gota',
  ],
  'Jaipur': [
    'C Scheme',
    'Malviya Nagar',
    'Vaishali Nagar',
    'Mansarovar',
    'Raja Park',
    'Bani Park',
    'Tonk Road',
    'Jagatpura',
    'Civil Lines',
    'Sodala',
    'Jhotwara',
    'Ajmer Road',
    'Vidhyadhar Nagar',
  ],
};
